# Build Docker image for this app using Azure Pipelines
# http://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts

variables:
  azure.vm_image: 'ubuntu-16.04'
  docker.root: '$(Agent.BuildDirectory)/s/docker'
  docker.id: 'fredrikaverpil'
  docker.image: 'oiio-centos7'

pool:
  vmImage: '$(azure.vm_image)'

steps:

- script: |
    cd $(docker.root)/centos7
    docker build -f Dockerfile -t $(docker.id)/$(docker.image) .
    # docker login -u $(dockerId) -p $pswd
    # docker push $(dockerId)/$(imageName)
  # env:
  #   pswd: $(dockerPassword)
  displayName: 'Build Docker image'
  # displayName: 'Build and push Docker image'