# Build openimageio for python

on:
  push:

  workflow_dispatch:


jobs:

  linux:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    # Build oiio
    - name: Build oiio
      run: |
        sudo apt update
        sudo apt-get install libboost-all-dev
        sudo apt-get install libjpeg-dev
        sudo apt-get install zlib1g-dev
        sudo apt-get install libpng-dev
        sudo apt-get install libtiff-dev
        sudo apt-get install libopenexr-dev
        git clone https://github.com/OpenImageIO/oiio.git --branch 2.2.10.1
        cd build
        cmake -DSTOP_ON_WARNING=0

      shell: bash
      env:
        OIIO_PYTHON_VERSION: "3.8"
